# Generated by Django 5.0.3 on 2024-05-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description_two',
        ),
        migrations.AddField(
            model_name='event',
            name='foto_four',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='foto_three',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
