# Generated by Django 5.0.3 on 2024-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_event_item_foto_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event_item',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.AddField(
            model_name='event_item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event_item',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event_item',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AddField(
            model_name='event_item',
            name='location',
            field=models.ManyToManyField(to='mainpage.locations'),
        ),
    ]
