# Generated by Django 5.0.3 on 2024-04-23 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_locations_remove_event_item_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_item',
            name='foto_file',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
