# Generated by Django 5.0.3 on 2024-04-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_event_item_foto_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_item',
            name='foto_file',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event_item',
            name='location',
            field=models.ManyToManyField(blank=True, to='mainpage.locations'),
        ),
    ]
