# Generated by Django 5.0.3 on 2024-05-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('mainpage', '0005_alter_event_item_foto_file_alter_event_item_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AlterField(
            model_name='event_item',
            name='location',
            field=models.ManyToManyField(blank=True, to='locations.locations'),
        ),
    ]
