# Generated by Django 5.0.3 on 2024-05-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_delete_locations_alter_event_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_item',
            name='link',
            field=models.TextField(),
        ),
    ]
