# Generated by Django 5.0.3 on 2024-05-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='foto_file',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='title',
        ),
    ]
