# Generated by Django 5.0.3 on 2024-05-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_recommendation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='date',
        ),
    ]
