# Generated by Django 5.0.3 on 2024-05-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_remove_recommendation_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='Recommendations',
        ),
    ]
