# Generated by Django 5.0.3 on 2024-05-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_rename_recommendation_recommendations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
