# Generated by Django 5.0.3 on 2024-05-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_recommendation_delete_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('foto_file', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
